// // Generated by Sketch Header Tool on 2026.01.10-17.11.24
// #include "Sketch.h"
// #include "Sketch/Public/Widgets/SSketchWidget.h"
// #include "SketchHeaderToolTypes.h"
//
// #include "Widgets/SRadialSlider.h"
// #include "Widgets/ColorGrading/SColorGradingComponentViewer.h"
// #include "Widgets/ColorGrading/SColorGradingPicker.h"
// #include "Widgets/ColorGrading/SColorGradingWheel.h"
// #include "Widgets/PropertyViewer/SBoolPropertyValue.h"
// #include "Widgets/PropertyViewer/SDefaultPropertyValue.h"
// #include "Widgets/PropertyViewer/SEnumPropertyValue.h"
// #include "Widgets/PropertyViewer/SNumericPropertyValue.h"
// #include "Widgets/PropertyViewer/SPropertyViewer.h"
// #include "Widgets/PropertyViewer/SStringPropertyValue.h"
//
// #define LOCTEXT_NAMESPACE "Sketch"
//
// PRAGMA_DISABLE_DEPRECATION_WARNINGS
//
// void RegisterRadialSlider(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("RadialSlider");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SRadialSlider::FArguments Arguments;
// 			Arguments
// 				.MouseUsesStep(Sketch("MouseUsesStep", bool(false)))
// 				.RequiresControllerLock(Sketch("RequiresControllerLock", bool(true)))
// 				.Locked(Sketch("Locked", bool(false)))
// 				.SliderBarColor(Sketch("SliderBarColor", FSlateColor(FLinearColor::Gray)))
// 				.SliderProgressColor(Sketch("SliderProgressColor", FSlateColor(FLinearColor::White)))
// 				.SliderHandleColor(Sketch("SliderHandleColor", FSlateColor(FLinearColor::White)))
// 				.CenterBackgroundColor(Sketch("CenterBackgroundColor", FSlateColor(FLinearColor::Transparent)))
// 				.Thickness(Sketch("Thickness", float()))
// 				// .CenterBackgroundBrush(Sketch("CenterBackgroundBrush", FSlateBrush( FSlateRoundedBoxBrush(FStyleColors::Transparent, FVector2D(90.0f, 90.0f)) )))
// 				.StepSize(Sketch("StepSize", float(0.01f)))
// 				.Value(Sketch("Value", float(1.f)))
// 				.bUseCustomDefaultValue(Sketch("bUseCustomDefaultValue", bool(false)))
// 				.CustomDefaultValue(Sketch("CustomDefaultValue", float(0.0f)))
// 				// .SliderRange(Sketch("SliderRange", FRuntimeFloatCurve(  )))
// 				.SliderHandleStartAngle(Sketch("SliderHandleStartAngle", float(60.0f)))
// 				.SliderHandleEndAngle(Sketch("SliderHandleEndAngle", float(300.0f)))
// 				.AngularOffset(Sketch("AngularOffset", float(0.0f)))
// 				.HandStartEndRatio(Sketch("HandStartEndRatio", FVector2D(FVector2D(0.0f, 1.0f))))
// 				// .ValueTags(Sketch("ValueTags", TArray<float>(  )))
// 				.IsFocusable(Sketch("IsFocusable", bool(true)))
// 				.UseVerticalDrag(Sketch("UseVerticalDrag", bool(false)))
// 				.ShowSliderHandle(Sketch("ShowSliderHandle", bool(true)))
// 				.ShowSliderHand(Sketch("ShowSliderHand", bool(false)))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SRadialSlider> Widget = SArgumentNew(Arguments, SRadialSlider);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
// }
//
// void RegisterColorGradingComponentViewer(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("ColorGradingComponentViewer");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SColorGradingComponentViewer::FArguments Arguments;
// 			Arguments
// 				.Value(Sketch("Value", TOptional<float>(0.f)))
// 				.Component(Sketch("Component", EColorGradingComponent()))
// 				.ColorGradingMode(Sketch("ColorGradingMode", EColorGradingModes()))
// 				.MinValue(Sketch("MinValue", TOptional<float>(0.f)))
// 				.MaxValue(Sketch("MaxValue", TOptional<float>(2.f)))
// 				.MinSliderValue(Sketch("MinSliderValue", TOptional<float>()))
// 				.MaxSliderValue(Sketch("MaxSliderValue", TOptional<float>()))
// 				.MinFractionalDigits(Sketch("MinFractionalDigits", TOptional<int32>(DefaultMinFractionalDigits)))
// 				.MaxFractionalDigits(Sketch("MaxFractionalDigits", TOptional<int32>(DefaultMaxFractionalDigits)))
// 				.Delta(Sketch("Delta", float(0.f)))
// 				.ShiftMultiplier(Sketch("ShiftMultiplier", float(10.f)))
// 				.CtrlMultiplier(Sketch("CtrlMultiplier", float(0.1f)))
// 				.LinearDeltaSensitivity(Sketch("LinearDeltaSensitivity", int32()))
// 				.SupportDynamicSliderMaxValue(Sketch("SupportDynamicSliderMaxValue", bool(false)))
// 				.SupportDynamicSliderMinValue(Sketch("SupportDynamicSliderMinValue", bool(false)))
// 				.SliderExponent(Sketch("SliderExponent", float(1.f)))
// 				.SliderExponentNeutralValue(Sketch("SliderExponentNeutralValue", float()))
// 				.WheelStep(Sketch("WheelStep", TOptional<float>()))
// 				// .TypeInterface(Sketch("TypeInterface", TSharedPtr<INumericTypeInterface<float>>(  )))
// 				.UseCompactDisplay(Sketch("UseCompactDisplay", bool(false)))
// 				.AllowSpin(Sketch("AllowSpin", bool(true)))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SColorGradingComponentViewer> Widget = SArgumentNew(Arguments, SColorGradingComponentViewer);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("ColorGrading"), MoveTemp(Factory));
// }
//
// void RegisterColorGradingPicker(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("ColorGradingPicker");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SColorGradingPicker::FArguments Arguments;
// 			Arguments
// 				.ValueMin(Sketch("ValueMin", TOptional<float>()))
// 				.ValueMax(Sketch("ValueMax", TOptional<float>()))
// 				.SliderValueMin(Sketch("SliderValueMin", TOptional<float>()))
// 				.SliderValueMax(Sketch("SliderValueMax", TOptional<float>()))
// 				.AllowSpin(Sketch("AllowSpin", bool(true)))
// 				.SupportDynamicSliderMaxValue(Sketch("SupportDynamicSliderMaxValue", bool(false)))
// 				.SupportDynamicSliderMinValue(Sketch("SupportDynamicSliderMinValue", bool(false)))
// 				.DesiredWheelSize(Sketch("DesiredWheelSize", int32()))
// 				.MainDelta(Sketch("MainDelta", float(0.01f)))
// 				.MainShiftMultiplier(Sketch("MainShiftMultiplier", float(10.f)))
// 				.MainCtrlMultiplier(Sketch("MainCtrlMultiplier", float(0.1f)))
// 				// ."Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported. Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move"(Sketch(""Shift Mouse Move Pixel Per Delta is deprecated and incrementing by a fixed delta per pixel is no longer supported. Please use ShiftMultiplier and CtrlMultiplier which will multiply the step per mouse move"", int32, MainShiftMouseMovePixelPerDelta, 5.4(  )))
// 				.ColorGradingModes(Sketch("ColorGradingModes", EColorGradingModes(EColorGradingModes::Saturation)))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SColorGradingPicker> Widget = SArgumentNew(Arguments, SColorGradingPicker);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("ColorGrading"), MoveTemp(Factory));
// }
//
// void RegisterColorGradingWheel(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("ColorGradingWheel");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SColorGradingWheel::FArguments Arguments;
// 			Arguments
// 				.SelectedColor(Sketch("SelectedColor", FLinearColor()))
// 				.DesiredWheelSize(Sketch("DesiredWheelSize", int32()))
// 				.ExponentDisplacement(Sketch("ExponentDisplacement", float()))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SColorGradingWheel> Widget = SArgumentNew(Arguments, SColorGradingWheel);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("ColorGrading"), MoveTemp(Factory));
// }
//
// void RegisterBoolPropertyValue(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("BoolPropertyValue");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SBoolPropertyValue::FArguments Arguments;
// 			Arguments
// 				// .Path(Sketch("Path", FPropertyPath(  )))
// 				// .NotifyHook(Sketch("NotifyHook", (INotifyHook*) nullptr ))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SBoolPropertyValue> Widget = SArgumentNew(Arguments, SBoolPropertyValue);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("PropertyViewer"), MoveTemp(Factory));
// }
//
// void RegisterDefaultPropertyValue(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("DefaultPropertyValue");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SDefaultPropertyValue::FArguments Arguments;
// 			Arguments
// 				// .Path(Sketch("Path", FPropertyPath(  )))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SDefaultPropertyValue> Widget = SArgumentNew(Arguments, SDefaultPropertyValue);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("PropertyViewer"), MoveTemp(Factory));
// }
//
// void RegisterEnumPropertyValue(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("EnumPropertyValue");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SEnumPropertyValue::FArguments Arguments;
// 			Arguments
// 				// .Path(Sketch("Path", FPropertyPath(  )))
// 				// .NotifyHook(Sketch("NotifyHook", (INotifyHook*) nullptr ))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SEnumPropertyValue> Widget = SArgumentNew(Arguments, SEnumPropertyValue);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("PropertyViewer"), MoveTemp(Factory));
// }
//
// void RegisterNumericPropertyValue(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("NumericPropertyValue");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SNumericPropertyValue::FArguments Arguments;
// 			Arguments
// 				// .Path(Sketch("Path", FPropertyPath(  )))
// 				// .NotifyHook(Sketch("NotifyHook", (INotifyHook*) nullptr ))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SNumericPropertyValue> Widget = SArgumentNew(Arguments, SNumericPropertyValue);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("PropertyViewer"), MoveTemp(Factory));
// }
//
// void RegisterPropertyViewer(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("PropertyViewer");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			TSharedRef<HeaderTool::FUniqueSlotMeta> Meta = MakeShared<HeaderTool::FUniqueSlotMeta>();
// 			Meta->Slots.Reserve(2);
// 			SPropertyViewer::FArguments Arguments;
// 			Arguments
// 				.PropertyVisibility(Sketch("PropertyVisibility", EPropertyVisibility()))
// 				.bSanitizeName(Sketch("bSanitizeName", bool()))
// 				.bShowFieldIcon(Sketch("bShowFieldIcon", bool()))
// 				.bSortChildNode(Sketch("bSortChildNode", bool()))
// 				.bShowSearchBox(Sketch("bShowSearchBox", bool()))
// 				.SelectionMode(Sketch("SelectionMode", ESelectionMode::Type()))
// 				// .FieldIterator(Sketch("FieldIterator", (IFieldIterator*) nullptr ))
// 				// .FieldExpander(Sketch("FieldExpander", (IFieldExpander*) nullptr ))
// 				// .NotifyHook(Sketch("NotifyHook", (INotifyHook*) nullptr ))
// 				// .OverrideIconColorSettings(Sketch("OverrideIconColorSettings", TOptional<const FFieldColorSettings>(  )))
// 				.SearchBoxPreSlot()[Meta->AddSlot(WidgetToTakeUniqueSlotsForm, FName(TEXT("SearchBoxPreSlot")))]
// 				.SearchBoxPostSlot()[Meta->AddSlot(WidgetToTakeUniqueSlotsForm, FName(TEXT("SearchBoxPostSlot")))]
// 				.AddMetaData(MoveTemp(Meta))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SPropertyViewer> Widget = SArgumentNew(Arguments, SPropertyViewer);
// 			return MoveTemp(Widget);
// 		};
// 	Factory.EnumerateUniqueSlots = &HeaderTool::FUniqueSlotMeta::GetSlots;
// 	Host.RegisterFactory(TEXT("PropertyViewer"), MoveTemp(Factory));
// }
//
// void RegisterStringPropertyValue(FSketchModule& Host)
// {
// 	using namespace sketch;
// 	FFactory Factory;
// 	Factory.Name = TEXT("StringPropertyValue");
// 	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsForm)
// 		{
// 			SStringPropertyValue::FArguments Arguments;
// 			Arguments
// 				// .Path(Sketch("Path", FPropertyPath(  )))
// 				// .NotifyHook(Sketch("NotifyHook", (INotifyHook*) nullptr ))
// 				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
// 			TSharedRef<SStringPropertyValue> Widget = SArgumentNew(Arguments, SStringPropertyValue);
// 			return MoveTemp(Widget);
// 		};
// 	Host.RegisterFactory(TEXT("PropertyViewer"), MoveTemp(Factory));
// }
//
//
// void RegisterAdvancedWidgetsFactories()
// {
// 	FSketchModule& Host = FSketchModule::Get();
// 	RegisterRadialSlider(Host);
// 	RegisterColorGradingComponentViewer(Host);
// 	RegisterColorGradingPicker(Host);
// 	RegisterColorGradingWheel(Host);
// 	RegisterBoolPropertyValue(Host);
// 	RegisterDefaultPropertyValue(Host);
// 	RegisterEnumPropertyValue(Host);
// 	RegisterNumericPropertyValue(Host);
// 	RegisterPropertyViewer(Host);
// 	RegisterStringPropertyValue(Host);
// }
//
// PRAGMA_ENABLE_DEPRECATION_WARNINGS
//
// #undef LOCTEXT_NAMESPACE
