// Generated by Sketch Header Tool on 2026.01.12-13.24.14
#include "Sketch.h"
#include "Sketch/Public/Widgets/SSketchWidget.h"
#include "SketchHeaderToolTypes.h"

#include "Widgets/SBoxPanel.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/SOverlay.h"
#include "Widgets/SWindow.h"
#include "Widgets/Images/SImage.h"

#define LOCTEXT_NAMESPACE "Sketch"

PRAGMA_DISABLE_DEPRECATION_WARNINGS

void RegisterHorizontalBox()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("HorizontalBox");
	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SHorizontalBox::FArguments Arguments;
			Arguments
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SHorizontalBox> Widget = SArgumentNew(Arguments, SHorizontalBox);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterVerticalBox()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("VerticalBox");
	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SVerticalBox::FArguments Arguments;
			Arguments
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SVerticalBox> Widget = SArgumentNew(Arguments, SVerticalBox);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterStackBox()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("StackBox");
	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SStackBox::FArguments Arguments;
			Arguments
				.Orientation(Sketch("Orientation", EOrientation()))
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SStackBox> Widget = SArgumentNew(Arguments, SStackBox);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterDragAndDropVerticalBox()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("DragAndDropVerticalBox");
	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SDragAndDropVerticalBox::FArguments Arguments;
			Arguments
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SDragAndDropVerticalBox> Widget = SArgumentNew(Arguments, SDragAndDropVerticalBox);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterOverlay()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("Overlay");
	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SOverlay::FArguments Arguments;
			Arguments
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SOverlay> Widget = SArgumentNew(Arguments, SOverlay);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterWindow()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("Window");
	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			TSharedRef<HeaderTool::FUniqueSlotMeta> Meta = MakeShared<HeaderTool::FUniqueSlotMeta>();
			Meta->Slots.Reserve(1);
			SWindow::FArguments Arguments;
			Arguments
				.Type(Sketch("Type", EWindowType(EWindowType::Normal)))
				.Title(Sketch("Title", FText()))
				.bDragAnywhere(Sketch("bDragAnywhere", bool(false)))
				.AutoCenter(Sketch("AutoCenter", EAutoCenter(EAutoCenter::PreferredWorkArea)))
				.ScreenPosition(Sketch("ScreenPosition", UE::Slate::FDeprecateVector2DParameter(FVector2f::ZeroVector)))
				.ClientSize(Sketch("ClientSize", UE::Slate::FDeprecateVector2DParameter(FVector2f::ZeroVector)))
				.AdjustInitialSizeAndPositionForDPIScale(Sketch("AdjustInitialSizeAndPositionForDPIScale", bool(true)))
				// .SupportsTransparency(Sketch("SupportsTransparency", FWindowTransparency( EWindowTransparency::None )))
				.InitialOpacity(Sketch("InitialOpacity", float(1.0f)))
				.IsInitiallyMaximized(Sketch("IsInitiallyMaximized", bool(false)))
				.IsInitiallyMinimized(Sketch("IsInitiallyMinimized", bool(false)))
				.SizingRule(Sketch("SizingRule", ESizingRule(ESizingRule::UserSized)))
				.IsPopupWindow(Sketch("IsPopupWindow", bool(false)))
				.IsTopmostWindow(Sketch("IsTopmostWindow", bool(false)))
				.FocusWhenFirstShown(Sketch("FocusWhenFirstShown", bool(true)))
				.FocusUserIndex(Sketch("FocusUserIndex", int32(INDEX_NONE)))
				.ActivationPolicy(Sketch("ActivationPolicy", EWindowActivationPolicy(EWindowActivationPolicy::Always)))
				.UseOSWindowBorder(Sketch("UseOSWindowBorder", bool(false)))
				.HasCloseButton(Sketch("HasCloseButton", bool(true)))
				.SupportsMaximize(Sketch("SupportsMaximize", bool(true)))
				.SupportsMinimize(Sketch("SupportsMinimize", bool(true)))
				.ShouldPreserveAspectRatio(Sketch("ShouldPreserveAspectRatio", bool(false)))
				.MinWidth(Sketch("MinWidth", TOptional<float>()))
				.MinHeight(Sketch("MinHeight", TOptional<float>()))
				.MaxWidth(Sketch("MaxWidth", TOptional<float>()))
				.MaxHeight(Sketch("MaxHeight", TOptional<float>()))
				.CreateTitleBar(Sketch("CreateTitleBar", bool(true)))
				.SaneWindowPlacement(Sketch("SaneWindowPlacement", bool(true)))
				.LayoutBorder(Sketch("LayoutBorder", FMargin(Arguments._Style->BorderPadding)))
				.UserResizeBorder(Sketch("UserResizeBorder", FMargin(FMargin(5, 5, 5, 5))))
				.bManualManageDPI(Sketch("bManualManageDPI", bool(false)))
				.CloseButtonToolTipText(Sketch("CloseButtonToolTipText", FText(NSLOCTEXT("SWindow", "Window_DefaultCloseButtonToolTip", "Close"))))
				.Content()[Meta->AddSlot(WidgetToTakeUniqueSlotsFrom, FName(TEXT("Content")))]
				.AddMetaData(MoveTemp(Meta))
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SWindow> Widget = SArgumentNew(Arguments, SWindow);
			return MoveTemp(Widget);
		};
	Factory.EnumerateUniqueSlots = &HeaderTool::FUniqueSlotMeta::GetSlots;
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterImage()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("Image");
	Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SImage::FArguments Arguments;
			Arguments
				.Image(Sketch("Image", (const FSlateBrush*)(FCoreStyle::Get().GetDefaultBrush())))
				.ColorAndOpacity(Sketch("ColorAndOpacity", FSlateColor(FLinearColor::White)))
				.DesiredSizeOverride(Sketch("DesiredSizeOverride", TOptional<FVector2D>()))
				.FlipForRightToLeftFlowDirection(Sketch("FlipForRightToLeftFlowDirection", bool(false)))
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SImage> Widget = SArgumentNew(Arguments, SImage);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Images"), MoveTemp(Factory));
}


void RegisterSlateCoreFactories()
{
	RegisterHorizontalBox();
	RegisterVerticalBox();
	RegisterStackBox();
	RegisterDragAndDropVerticalBox();
	RegisterOverlay();
	RegisterWindow();
	RegisterImage();
}

PRAGMA_ENABLE_DEPRECATION_WARNINGS

#undef LOCTEXT_NAMESPACE
