// Generated by Sketch Header Tool on 2026.05.11-17.44.17
#include "Sketch.h"
#include "Sketch/Public/Widgets/SSketchWidget.h"
#include "HeaderTool/SketchWidgetFactoryTools.h"

#include "Widgets/Images/SImage.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/SOverlay.h"
#include "Widgets/SWindow.h"

#define LOCTEXT_NAMESPACE "Sketch"

PRAGMA_DISABLE_DEPRECATION_WARNINGS

void RegisterImage()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("Image";)
		Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SImage::FArguments Arguments;
			Arguments
				.Image(Sketch(TEXT("Image"), (const FSlateBrush*)(FCoreStyle::Get().GetDefaultBrush())))
				.ColorAndOpacity(Sketch(TEXT("ColorAndOpacity"), FSlateColor(FLinearColor::White)))
				.DesiredSizeOverride(Sketch(TEXT("DesiredSizeOverride")).operator TOptional<FVector2D>())
				.FlipForRightToLeftFlowDirection(Sketch(TEXT("FlipForRightToLeftFlowDirection"), bool(false)))
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SImage> Widget = SArgumentNew(Arguments, SImage);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Images"), MoveTemp(Factory));
}

void RegisterHorizontalBox()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("HorizontalBox";)
		Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SHorizontalBox::FArguments Arguments;
			Arguments
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SHorizontalBox> Widget = SArgumentNew(Arguments, SHorizontalBox);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterVerticalBox()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("VerticalBox";)
		Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SVerticalBox::FArguments Arguments;
			Arguments
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SVerticalBox> Widget = SArgumentNew(Arguments, SVerticalBox);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterStackBox()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("StackBox";)
		Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SStackBox::FArguments Arguments;
			Arguments
				.Orientation(Sketch(TEXT("Orientation")).operator EOrientation())
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SStackBox> Widget = SArgumentNew(Arguments, SStackBox);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterDragAndDropVerticalBox()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("DragAndDropVerticalBox";)
		Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SDragAndDropVerticalBox::FArguments Arguments;
			Arguments
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SDragAndDropVerticalBox> Widget = SArgumentNew(Arguments, SDragAndDropVerticalBox);
			return MoveTemp(Widget);
		};
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterOverlay()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("Overlay";)
		Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			SOverlay::FArguments Arguments;
			Arguments
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SOverlay> Widget = SArgumentNew(Arguments, SOverlay);
			return MoveTemp(Widget);
		};
	Factory.EnumerateDynamicSlotTypes = [](const SWidget& Widget)->sketch::FFactory::FDynamicSlotTypes
		{
			sketch::FFactory::FDynamicSlotTypes Result;
			Result.Reserve(1);
			Result = { TEXT("FOverlaySlot"), };
			return Result;
		};
	Factory.ConstructDynamicSlot = [](SWidget& Widget, const FName& SlotType) -> ::FSlotBase&
		{
			check(SlotType == TEXT("FOverlaySlot"));
			SOverlay::FOverlaySlot* Slot;
			{
				decltype(auto) SlotArgs = static_cast<SOverlay&>(Widget).AddSlot();
				SlotArgs
					.Padding(Sketch(TEXT("Padding")).operator FMargin())
					.HAlign(Sketch(TEXT("HAlign"), EHorizontalAlignment(HAlign_Fill)))
					.VAlign(Sketch(TEXT("VAlign"), EVerticalAlignment(VAlign_Fill)))
					.ZOrder(Sketch(TEXT("ZOrder")).operator TOptional<int32>())
					;
				Slot = SlotArgs.GetSlot();
			}
			return *Slot;
		};
	Factory.DestroyDynamicSlot = &HeaderTool::DestroyDynamicSlot<SOverlay>;
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}

void RegisterWindow()
{
	using namespace sketch;
	FFactory Factory;
	Factory.Name = TEXT("Window";)
		Factory.ConstructWidget = [](SWidget* WidgetToTakeUniqueSlotsFrom)
		{
			TSharedRef<HeaderTool::FUniqueSlotMeta> Meta = MakeShared<HeaderTool::FUniqueSlotMeta>();
			Meta->Slots.Reserve(1);
			SWindow::FArguments Arguments;
			Arguments
				.Type(Sketch(TEXT("Type"), EWindowType(EWindowType::Normal)))
				.Title(Sketch(TEXT("Title")).operator FText())
				.bDragAnywhere(Sketch(TEXT("bDragAnywhere"), bool(false)))
				.AutoCenter(Sketch(TEXT("AutoCenter"), EAutoCenter(EAutoCenter::PreferredWorkArea)))
				.ScreenPosition(Sketch(TEXT("ScreenPosition"), UE::Slate::FDeprecateVector2DParameter(FVector2f::ZeroVector)))
				.ClientSize(Sketch(TEXT("ClientSize"), UE::Slate::FDeprecateVector2DParameter(FVector2f::ZeroVector)))
				.AdjustInitialSizeAndPositionForDPIScale(Sketch(TEXT("AdjustInitialSizeAndPositionForDPIScale"), bool(true)))
				// .SupportsTransparency(Sketch(TEXT("SupportsTransparency"), FWindowTransparency( EWindowTransparency::None )))
				.InitialOpacity(Sketch(TEXT("InitialOpacity"), float(1.0f)))
				.IsInitiallyMaximized(Sketch(TEXT("IsInitiallyMaximized"), bool(false)))
				.IsInitiallyMinimized(Sketch(TEXT("IsInitiallyMinimized"), bool(false)))
				.SizingRule(Sketch(TEXT("SizingRule"), ESizingRule(ESizingRule::UserSized)))
				.IsPopupWindow(Sketch(TEXT("IsPopupWindow"), bool(false)))
				.IsTopmostWindow(Sketch(TEXT("IsTopmostWindow"), bool(false)))
				.FocusWhenFirstShown(Sketch(TEXT("FocusWhenFirstShown"), bool(true)))
				.FocusUserIndex(Sketch(TEXT("FocusUserIndex"), int32(INDEX_NONE)))
				.ActivationPolicy(Sketch(TEXT("ActivationPolicy"), EWindowActivationPolicy(EWindowActivationPolicy::Always)))
				.UseOSWindowBorder(Sketch(TEXT("UseOSWindowBorder"), bool(false)))
				.HasCloseButton(Sketch(TEXT("HasCloseButton"), bool(true)))
				.SupportsMaximize(Sketch(TEXT("SupportsMaximize"), bool(true)))
				.SupportsMinimize(Sketch(TEXT("SupportsMinimize"), bool(true)))
				.ShouldPreserveAspectRatio(Sketch(TEXT("ShouldPreserveAspectRatio"), bool(false)))
				.MinWidth(Sketch(TEXT("MinWidth")).operator TOptional<float>())
				.MinHeight(Sketch(TEXT("MinHeight")).operator TOptional<float>())
				.MaxWidth(Sketch(TEXT("MaxWidth")).operator TOptional<float>())
				.MaxHeight(Sketch(TEXT("MaxHeight")).operator TOptional<float>())
				.CreateTitleBar(Sketch(TEXT("CreateTitleBar"), bool(true)))
				.SaneWindowPlacement(Sketch(TEXT("SaneWindowPlacement"), bool(true)))
				.LayoutBorder(Sketch(TEXT("LayoutBorder"), FMargin(Arguments._Style->BorderPadding)))
				.UserResizeBorder(Sketch(TEXT("UserResizeBorder"), FMargin(FMargin(5, 5, 5, 5))))
				.bManualManageDPI(Sketch(TEXT("bManualManageDPI"), bool(false)))
				.CloseButtonToolTipText(Sketch(TEXT("CloseButtonToolTipText"), FText(NSLOCTEXT("SWindow", "Window_DefaultCloseButtonToolTip", "Close"))))
				.Content()[Meta->AddSlot(WidgetToTakeUniqueSlotsFrom, TEXT("Content"))]
				.AddMetaData(MoveTemp(Meta))
				.SKETCH_WIDGET_FACTORY_BOILERPLATE();
			TSharedRef<SWindow> Widget = SArgumentNew(Arguments, SWindow);
			return MoveTemp(Widget);
		};
	Factory.EnumerateUniqueSlots = &HeaderTool::FUniqueSlotMeta::GetSlots;
	FSketchCore& Core = FSketchCore::Get();
	Core.RegisterFactory(TEXT("Widgets"), MoveTemp(Factory));
}


void RegisterSlateCoreFactories()
{
	RegisterImage();
	RegisterHorizontalBox();
	RegisterVerticalBox();
	RegisterStackBox();
	RegisterDragAndDropVerticalBox();
	RegisterOverlay();
	RegisterWindow();
}

PRAGMA_ENABLE_DEPRECATION_WARNINGS

#undef LOCTEXT_NAMESPACE
